# Lesson 2 Practice: NumPy Part 2
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L02-Numpy_Part2-Lesson.ipynb](./L02-Numpy_Part2-Lesson.ipynb).  


## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired. 

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [1]:
import numpy as np

## Task 2a: Indexing by Subsetting and Slicing

In the practice notebook perform the following:

1. Create (or re-use) 3 arrays, each containing three dimensions.
2. Slice each of these arrays so that:
    + One element / number is returned.
    + One dimension is returned.
    + A subset of a dimension is returned.
3. What is the difference between `[x:]` and `[x, ...]`? (hint, try each on high-dimension arrays).
    
*Exactly what you choose to return is not imporant at this point, the goal of this task is to train you so that if you are given an n-dimension NumPy array, you can write an index or slice that returns a subset of desired positions.*

In [2]:
ary_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ary_1[1,2])
ary_2 = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(ary_2[2,0])
ary_3 = np.array([[0,4,8],[0,15,16],[0,23,42]])
print(ary_3[0,1])
print(ary_1[1:2])
print(ary_2[0:1])
print(ary_3[1:2])
print(ary_1[1:])
print(ary_2[0:2])
print(ary_3[0:2])

# 3 x: gets specified dimension from array; x,... gets the specified dimension and element from array

6
3
4
[[4 5 6]]
[[1 1 1]]
[[ 0 15 16]]
[[4 5 6]
 [7 8 9]]
[[1 1 1]
 [2 2 2]]
[[ 0  4  8]
 [ 0 15 16]]


## Task 3a: Boolean Indexing

In the practice notebook perform the following:

+ Experiment with the following boolean conditionals to generate boolean arrays for indexing:
  + Greater than
  + Less than
  + Equals
  + Combine two or more of the above with:
      + or `|`
      + and `&`

You can create arrays or use existing ones

In [3]:
x = np.array([[0.01,0.02,0.03],[0.1, 0.2, 0.3],[0.5,0.6,0.7],[0.8,0.9,0.93]])
x[x > 0.2]
x[x < 0.1]
x[x = 0.5]
x[(0.3 < x) & (x > 0.1)]
x[(x < 0.2) | (x > 0.89)]

SyntaxError: invalid syntax (<ipython-input-3-45a8d1a95913>, line 4)

## Task 4a: Getting Help

In the practice notebook perform the following:

+ In the code cell below, call `help()` on two of the following functions: `np.transpose()`, `np.reshape()`, `np.resize()`, `np.ravel()`, `np.append()`, `np.delete()`, `np.concatenate()`, `np.vstack()`, `np.hstack()`, `np.column_stack()`, `np.vsplit()`, `np.hsplit()` 
+ Respond to this question: Did you understand the help docuemntation? Could you use the function just by looking at what the help says about it?  

In [ ]:
np.array([[1,2,3,4,5,6,7],[7,6,5,4,3,2,1]])
xt = np.transpose(x)
a = np.array([0])
xa = np.append(x,a)
help(xt)
help(xa)
# I think I could mostly understand what the help() call does and the associated documentation. If I needed more help
# I would ask for help

## Task 5a: Transposing an Array

In the practice notebook perform the following:

+ Create a matrix of any size and transpose it.

In [ ]:
x = np.array([[1,2,3,4,5,6,7],[7,6,5,4,3,2,1]])
xt = np.transpose(x)
print(x)
print(xt)

## Task 5b: Reshaping an Array

In the practice notebook peform the following:

+ Create a matrix and resize it by adding 2 extra columns
+ Create a matrix and resize it by adding 1 extra row
+ Create a matrix of 8 x 2 and resize it to 4 x 4

In [ ]:
x = np.array([4,8,15,16])
y = np.append(x, [23,42])
print(y)

z = np.vstack((y, y))
print(z)

a = np.random.random((8,2))
print(a.reshape((4,4)))

## Task 5c: Appending to an Array

In the practice notebook perform the following:

 + Create a three dimensional array and append another row to the array
 + Append another colum to the array
 + Print the final results

In [ ]:
x = np.random.random((3,3))
a = np.random.random(3)
b = np.random.random(4)
c = np.vstack((x,a))
d = np.transpose(b)
e = np.append(c,d)
print(e)

## Task 5d: Inserting and Deleting Elements

In the practice notebook perform the following:

+ Examine the `help()` documentation for how to use the `insert()` and `delete()` functions.
+ Create a matrix and practice inserting a row and deleting a column.

In [17]:
x = np.array([[3,3,3],[3,3,3]])
b = np.array([1,2,3])
y = np.insert((x, b, 1, 1)
c = np.delete(y,[b])
print(z)

SyntaxError: invalid syntax (<ipython-input-17-fda8467fee5f>, line 4)

## Task 5e: Joining Arrays

In the practice notebook perform the following:

+ Execute the code (in the cell below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [4]:
# Concatentate `my_array` and `x`: similar to np.append()
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
print(np.concatenate((my_array, x)))

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
print(np.vstack((my_array, my_2d_array)))

# Stack arrays horizontally
print("\nhstack:")
print(np.hstack((my_2d_array, my_2d_array)))

# Stack arrays column-wise
print("\ncolumn_stack:")
print(np.column_stack((my_2d_array, my_2d_array)))

concatenate:
[1 2 3 4 1 1 1 1]

vstack:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]

hstack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]

column_stack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


## Task 5d: Splitting Arrays

In the practice notebook perform the following:

+ Execute the code (as shown below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [18]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
print(np.hsplit(my_2d_array, 2))

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
print(np.vsplit(my_2d_array, 2))

original:
[[1 2 3 4]
 [5 6 7 8]]

hsplit:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

vsplit:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
