# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [1]:
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [2]:
array_1 = np.array([1,2,3])
array_2 = np.array([[1,2,3], [4,5,6]])
array_3 = np.array([[4,8], [15,16], [23,42]])


print(array_1)
print(array_2)
print(array_3)


[1 2 3]
[[1 2 3]
 [4 5 6]]
[[ 4  8]
 [15 16]
 [23 42]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [3]:
# defines my array
my_array = np.array([[1,2,3,4], [5,6,7,8], [9,0,1,2]])

# prints dimenstion for the array
print(my_array.ndim)

# prints the size of the matrix
print(my_array.shape)

# prints number of elements
print(my_array.size)

# prints data type
print(my_array.dtype)

# prints number of items in the array
print(my_array.itemsize)

# prints  amount of bytes of memory it consumes
print(my_array.data)


# prints number of bytes the array is
print(my_array.nbytes)

2
(3, 4)
12
int32
4
48


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [4]:
uno = np.ones((3, 4))
zeros = np.zeros((4, 5))
empt = np.empty((3, 4))
ful = np.full((2, 2), 4)
arng = np.arange((4))
lspace = np.linspace(1, 3, num=2)
ran = np.random.random()

print(uno)
print(zeros)
print(empt)
print(ful)
print(arng)
print(lspace)
print(ran)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1.13903885e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.37961302e-306 1.13003869e-042 2.21608617e-056 1.02254773e+166]
 [2.33858626e-052 1.54834143e+185 4.79601626e-037 4.74972496e+174]]
[[4 4]
 [4 4]]
[0 1 2 3]
[1. 3.]
0.3609007158550752


## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [19]:
a = np.ones((4,1,3))
b = np.random.random((5,3))

a + b
a * b
b - a

c = np.ones((5,5,5))
d = np.ones((2,3,4))

c * d


ValueError: operands could not be broadcast together with shapes (5,5,5) (2,3,4) 

## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [69]:
a = np.ones((3,3,3))
b = np.ones((2,2))
c = np.full((2,2), 5)

#looks for min betweent two matrices
np.minimum(b,c)
#looks for max between b and c
np.maximum(b,c)
#sums up each element
np.cumsum(b)
#finds mean of matric c
np.mean(c)
# finds correlation coefficient between c*b and c
np.corrcoef(c*b,c)
# looks at standard deviation of b*c
np.std(b*c)
#looks at variance of a 
np.var(a)


0.0

## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [75]:
a = [True, False, True, False]
b = [False, True, False, True]

#uses logical and to compare a and b
np.logical_and(a,b)

# uses logical or to compare a and b
np.logical_or(a,b)

#finds the elements with false values
np.logical_not(a)

array([False,  True, False,  True])